apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
        - name: library-app-container
          image: verooantezana/library-app:latest  
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: library-app-service
spec:
  type: NodePort  
  selector:
    app: library-app
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80    
      nodePort: 30007  
